sudo: false
language: python
python:
  - "2.7"
  - "3.6"
env:
  - TESTPREFIX=py
  - TESTPREFIX=cram
before_install:
  - pip install --quiet tox
script:
  - export TOXENV="${TESTPREFIX}$(echo $TRAVIS_PYTHON_VERSION | sed 's/\.//')"
  - echo "$TOXENV"
  - tox
